//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinevans.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinevans.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beoordeling van bioscoopgebruikers:.
        /// </summary>
        public static string BeoordelingTitel {
            get {
                return ResourceManager.GetString("BeoordelingTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string Beschrijving {
            get {
                return ResourceManager.GetString("Beschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw betaling is voltooid.
        /// </summary>
        public static string BetaalingVoltooid {
            get {
                return ResourceManager.GetString("BetaalingVoltooid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalen.
        /// </summary>
        public static string Betalen {
            get {
                return ResourceManager.GetString("Betalen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze week in de bioscoop.
        /// </summary>
        public static string DezeWeekIndeBioscoop {
            get {
                return ResourceManager.GetString("DezeWeekIndeBioscoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinsdag.
        /// </summary>
        public static string Dinsdag {
            get {
                return ResourceManager.GetString("Dinsdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donderdag.
        /// </summary>
        public static string Donderdag {
            get {
                return ResourceManager.GetString("Donderdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres is ongeldig.
        /// </summary>
        public static string EmailOngeldig {
            get {
                return ResourceManager.GetString("EmailOngeldig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres is verplicht.
        /// </summary>
        public static string EmailVerplicht {
            get {
                return ResourceManager.GetString("EmailVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmoverzicht.
        /// </summary>
        public static string Filmoverzicht {
            get {
                return ResourceManager.GetString("Filmoverzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        public static string Films {
            get {
                return ResourceManager.GetString("Films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijven.
        /// </summary>
        public static string Inschrijven {
            get {
                return ResourceManager.GetString("Inschrijven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaartjes.
        /// </summary>
        public static string Kaartjes {
            get {
                return ResourceManager.GetString("Kaartjes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaartjes overzicht.
        /// </summary>
        public static string KaartjesOverzicht {
            get {
                return ResourceManager.GetString("KaartjesOverzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies hier uw kaartjes.
        /// </summary>
        public static string KiesHierUwKaartjes {
            get {
                return ResourceManager.GetString("KiesHierUwKaartjes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengte.
        /// </summary>
        public static string Lengte {
            get {
                return ResourceManager.GetString("Lengte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log uit.
        /// </summary>
        public static string LogUit {
            get {
                return ResourceManager.GetString("LogUit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maandag.
        /// </summary>
        public static string Maandag {
            get {
                return ResourceManager.GetString("Maandag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuten.
        /// </summary>
        public static string Minuten {
            get {
                return ResourceManager.GetString("Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands gesproken.
        /// </summary>
        public static string NederlandsGesproken {
            get {
                return ResourceManager.GetString("NederlandsGesproken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuw account.
        /// </summary>
        public static string NieuwAccount {
            get {
                return ResourceManager.GetString("NieuwAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onthoud mij.
        /// </summary>
        public static string OnthoudMij {
            get {
                return ResourceManager.GetString("OnthoudMij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaartjes nu printen.
        /// </summary>
        public static string PrintKaartje {
            get {
                return ResourceManager.GetString("PrintKaartje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaartjes in de bioscoop printen.
        /// </summary>
        public static string PrintKaartjeBios {
            get {
                return ResourceManager.GetString("PrintKaartjeBios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisseurs.
        /// </summary>
        public static string Regisseurs {
            get {
                return ResourceManager.GetString("Regisseurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreer.
        /// </summary>
        public static string Registreer {
            get {
                return ResourceManager.GetString("Registreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreer als nieuwe gebruiker.
        /// </summary>
        public static string RegistreerNieuw {
            get {
                return ResourceManager.GetString("RegistreerNieuw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollen.
        /// </summary>
        public static string Rollen {
            get {
                return ResourceManager.GetString("Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolstoel toegankelijk.
        /// </summary>
        public static string RolstoelToegankelijk {
            get {
                return ResourceManager.GetString("RolstoelToegankelijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrijf je nu in voor de niewsbrief!.
        /// </summary>
        public static string SchrijfIn {
            get {
                return ResourceManager.GetString("SchrijfIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorteeropties.
        /// </summary>
        public static string Sorteeropties {
            get {
                return ResourceManager.GetString("Sorteeropties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starttijd.
        /// </summary>
        public static string Starttijd {
            get {
                return ResourceManager.GetString("Starttijd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        public static string Terug {
            get {
                return ResourceManager.GetString("Terug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaalprijs.
        /// </summary>
        public static string Totaalprijs {
            get {
                return ResourceManager.GetString("Totaalprijs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer uw betaalcode in.
        /// </summary>
        public static string VoerUwBetaalCodeIn {
            get {
                return ResourceManager.GetString("VoerUwBetaalCodeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorstellingen.
        /// </summary>
        public static string Voorstellingen {
            get {
                return ResourceManager.GetString("Voorstellingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijdag.
        /// </summary>
        public static string Vrijdag {
            get {
                return ResourceManager.GetString("Vrijdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string Wachtwoord {
            get {
                return ResourceManager.GetString("Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord bevestigen.
        /// </summary>
        public static string WachtwoordBevestigen {
            get {
                return ResourceManager.GetString("WachtwoordBevestigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wachtwoord moet minstens {2} karakters lang zijn..
        /// </summary>
        public static string WachtwoordEis {
            get {
                return ResourceManager.GetString("WachtwoordEis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord is ongeldig.
        /// </summary>
        public static string WachtwoordOngeldig {
            get {
                return ResourceManager.GetString("WachtwoordOngeldig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De wachtwoorden komen niet overeen..
        /// </summary>
        public static string WachtwoordOvereen {
            get {
                return ResourceManager.GetString("WachtwoordOvereen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord is verplicht.
        /// </summary>
        public static string WachtwoordVerplicht {
            get {
                return ResourceManager.GetString("WachtwoordVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woensdag.
        /// </summary>
        public static string Woensdag {
            get {
                return ResourceManager.GetString("Woensdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaal.
        /// </summary>
        public static string Zaal {
            get {
                return ResourceManager.GetString("Zaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaterdag.
        /// </summary>
        public static string Zaterdag {
            get {
                return ResourceManager.GetString("Zaterdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zondag.
        /// </summary>
        public static string Zondag {
            get {
                return ResourceManager.GetString("Zondag", resourceCulture);
            }
        }
    }
}
