// <auto-generated />
namespace Cinevans.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_seatId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_seatId));
        
        string IMigrationMetadata.Id
        {
            get { return "201603011331299_changed_seatId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
