// <auto-generated />
namespace Cinevans.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orderid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderid));
        
        string IMigrationMetadata.Id
        {
            get { return "201603161249380_orderid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
